apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-autoscale
  template:
    metadata:
      labels:
        app: nginx-autoscale
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            # Importante: o HPA precisa de requests/limits
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

